"""user table

Revision ID: 729162c2fcb0
Revises: ed11c520fa5a
Create Date: 2019-01-14 10:42:22.096855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729162c2fcb0'
down_revision = 'ed11c520fa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
